// <auto-generated />
namespace LightweightMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class make_year_mileage_nullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(make_year_mileage_nullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201408040404401_make_year_mileage_nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
